# Generated by Django 5.2.9 on 2025-12-25 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('quantity', models.IntegerField(default=1, verbose_name='Jumlah Total')),
                ('available', models.IntegerField(default=1, verbose_name='Jumlah Tersedia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Ditambahkan')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200, verbose_name='Nama Peminjam')),
                ('quantity', models.IntegerField(default=1, verbose_name='Jumlah Dipinjam')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Peminjaman')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Pengembalian')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Sudah Dikembalikan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='webapp.item', verbose_name='Barang')),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Peminjaman',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
